name: community_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.3.1
  calendar_date_picker2: ^2.0.0
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  geolocator: ^14.0.1
  device_info_plus: ^10.0.1
  package_info_plus: ^8.3.0
  crypto: ^3.0.6
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_animate: ^4.4.0
  get_storage: ^2.1.1
  http: ^1.1.0
  month_year_picker: ^0.5.0+1
  fl_chart: ^0.68.0
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  month_picker_dialog: ^6.3.0
  sqflite: ^2.4.2
  uuid: ^4.5.1
  path_provider: ^2.1.5
  dropdown_search: ^6.0.2
  readmore: ^3.0.0
  cached_network_image: ^3.4.1
  sensors_plus: ^6.1.1
  pedometer: ^4.1.1
  path: ^1.9.0
  shared_preferences: ^2.5.3
  flutter_html: ^3.0.0
  dio: ^5.9.0
  open_filex: ^4.7.0
  http_parser: ^4.1.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  firebase_crashlytics: ^5.0.1
  qr_flutter: ^4.1.0



  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/housing/
    - assets/images/health/
    - assets/images/parenting/
    - assets/images/doctor/
    - assets/images/applyforhelp/
    - assets/images/justice/
    - assets/images/social/
    - assets/images/internet_support/
    - assets/images/food_support/
    - assets/images/culture/
    - assets/images/disability/
    - assets/images/preloved/
    - assets/images/education/
    - assets/images/e_store/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
